# Generated by Django 5.0.6 on 2024-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=6, verbose_name='Codigo Registro'),
        ),
    ]
